#!/bin/bash
set -e

source "$(dirname "${BASH_SOURCE[0]}")/util.bash"

ensure_go_binary godep github.com/tools/godep
ensure_go_binary errcheck github.com/kisielk/errcheck

target="${root_path}/lookify"

set -x
go fmt .
go vet .
godep go build -o "${target}"

config_errcheck
run_errcheck

git rev-parse HEAD > REVISION
